services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser        # имя пользователя
      POSTGRES_PASSWORD: mypassword # пароль
      POSTGRES_DB: mydatabase       # имя базы
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # сохраняем данные в томе
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d mydatabase" ]
      interval: 3s
      timeout: 3s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: fastapi_server
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  client:
    build:
      context: ./client
    container_name: vue_client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - server

volumes:
  postgres_data: