services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser        # имя пользователя
      POSTGRES_PASSWORD: mypassword # пароль
      POSTGRES_DB: mydatabase       # имя базы
    ports:
      - "5433:5432"   # пробрасываем порт: хост:контейнер
    volumes:
      - postgres_data:/var/lib/postgresql/data  # сохраняем данные в томе

  client:
    build:
      context: ./client
    container_name: vue_client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  postgres_data: