"""set null group

Revision ID: 37392a8e0369
Revises: d3ac670ed90d
Create Date: 2025-09-26 13:05:28.449553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37392a8e0369'
down_revision: Union[str, Sequence[str], None] = 'd3ac670ed90d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('groups_instructor_id_fkey'), 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'instructors', ['instructor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key(op.f('groups_instructor_id_fkey'), 'groups', 'instructors', ['instructor_id'], ['id'])
    # ### end Alembic commands ###
