"""init

Revision ID: 675d73dc93c1
Revises: 
Create Date: 2025-09-15 20:15:51.600460

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '675d73dc93c1'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('groups_name_key'), 'groups', type_='unique')
    op.drop_column('groups', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('groups_name_key'), 'groups', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
