"""department-student fk

Revision ID: 9ddf9881e05b
Revises: f7667483b640
Create Date: 2025-09-19 13:57:49.029319

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9ddf9881e05b'
down_revision: str | Sequence[str] | None = 'f7667483b640'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('department_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'students', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'department_id')
    # ### end Alembic commands ###
