"""test cascade

Revision ID: a6d8eca80cd1
Revises: 675d73dc93c1
Create Date: 2025-09-19 12:44:38.509794

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a6d8eca80cd1'
down_revision: str | Sequence[str] | None = '675d73dc93c1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('student_subject_table_student_id_fkey'), 'student_subject_table', type_='foreignkey')
    op.create_foreign_key(None, 'student_subject_table', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_subject_table', type_='foreignkey')
    op.create_foreign_key(op.f('student_subject_table_student_id_fkey'), 'student_subject_table', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###
