"""nullale marks

Revision ID: c84cceb78e0d
Revises: a6d8eca80cd1
Create Date: 2025-09-19 13:10:01.518380

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'c84cceb78e0d'
down_revision: str | Sequence[str] | None = 'a6d8eca80cd1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
