"""set null group_id on delete

Revision ID: d3ac670ed90d
Revises: d5cd238d0a26
Create Date: 2025-09-26 02:17:12.067534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3ac670ed90d'
down_revision: Union[str, Sequence[str], None] = 'd5cd238d0a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('students_group_id_fkey'), 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'groups', ['group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(op.f('students_group_id_fkey'), 'students', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###
