"""nullable true group

Revision ID: d5cd238d0a26
Revises: 16cd97e381b2
Create Date: 2025-09-26 02:00:15.929314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5cd238d0a26'
down_revision: Union[str, Sequence[str], None] = '16cd97e381b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'instructor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'instructor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
