"""delete table

Revision ID: f7667483b640
Revises: e81551a49344
Create Date: 2025-09-19 13:53:37.435007

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f7667483b640'
down_revision: str | Sequence[str] | None = 'e81551a49344'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department_student_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_student_table',
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('department_student_table_department_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('department_student_table_student_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'department_id', name=op.f('department_student_table_pkey'))
    )
    # ### end Alembic commands ###
